Repository chachacreate/chachacreate_be, pull requests merged in 2025-09, with the labels that each got.

#113 feat: 클래스 예약조회 요약 API 정렬 필터/ 검색 추가
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/controller/ClassReservationQueryController.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/dto/response/ClassReservationSummaryResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/repository/ClassReservationQueryRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/service/ClassReservationQueryService.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/service/serviceimpl/ClassReservationQueryServiceImpl.java
Labels: ✨ feat

#122 🐛 fix: 구매자 마이페이지 클래스 예약 응답 데이터 추가
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/dto/response/ClassReservationSummaryResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/repository/ClassReservationQueryRepository.java
Labels: 🐛 fix

#132 🐛 fix: 구매자 마이페이지 클래스 예약 응답 클래스ID추가
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/dto/response/ClassReservationSummaryResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/repository/ClassReservationQueryRepository.java
Labels: 🐛 fix

#137 ✨ feat: 특정 스토어의 클래스 목록 조회 기능 통합 구현
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/controller/ClassListController.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/dto/request/ClassListFilterDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/repository/ClassInfoRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/ClassListService.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/serviceimpl/ClassListServiceImpl.java
Labels: ✨ feat

#171 ✨feat: 판매자 상품 정산 api 추가
  src/main/java/com/create/chacha/domains/seller/areas/settlement/controller/SellerSettlementClassesController.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/controller/SellerSettlementProductsController.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/dto/response/StoreSettlementAccountDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/SellerSettlementService.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/serviceimpl/SellerSettlementServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/SellerProductSettlementRepository.java
Labels: ✨ feat

#173 ✨ feat: 판매자 전체 정산 정보 조회 api 추가
  src/main/java/com/create/chacha/domains/seller/areas/settlement/controller/SellerSettlementMainController.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/SellerSettlementService.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/serviceimpl/SellerSettlementServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/SellerMainSettlementRepository.java
Labels: ✨ feat

#176 ✨ feat: 회원 권한 조회, 회원 권한 업데이트 함수 추가
  src/main/java/com/create/chacha/common/constants/ResponseCode.java
  src/main/java/com/create/chacha/config/exception/GlobalExceptionHandler.java
  src/main/java/com/create/chacha/domains/shared/member/controller/AuthController.java
  src/main/java/com/create/chacha/domains/shared/member/dto/request/MemberRoleUpdateRequestDTO.java
  src/main/java/com/create/chacha/domains/shared/member/exception/InvalidMemberRoleException.java
  src/main/java/com/create/chacha/domains/shared/member/exception/MemberRoleUpdateException.java
  src/main/java/com/create/chacha/domains/shared/member/exception/UnauthorizedRoleUpdateException.java
  src/main/java/com/create/chacha/domains/shared/member/service/MemberLoginService.java
  src/main/java/com/create/chacha/domains/shared/member/service/MemberRoleService.java
  src/main/java/com/create/chacha/domains/shared/member/serviceimpl/MemberLoginServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/member/serviceimpl/MemberRoleServiceImpl.java
Labels: ✨ feat

#178 ✨ feat: 판매자 클래스 매출 조회 api 추가
  src/main/java/com/create/chacha/domains/seller/areas/settlement/controller/ClassSalesController.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/dto/response/ClassSalesResponseDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/SellerSettlementService.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/serviceimpl/SellerSettlementServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/ClassSalesRepository.java
Labels: ✨ feat

#190 ♻️ refactor: 주문 취소/환불 API를 RESTful한 URL 구조로 변경
  src/main/java/com/create/chacha/domains/buyer/areas/mypage/controller/CancelRefundController.java
  src/main/java/com/create/chacha/domains/buyer/areas/mypage/dto/request/CancelRefundRequestDTO.java
Labels: ♻️ refactor

#191 ✨ feat: 구매자 마이페이지 리뷰 조회 api 추가
  src/main/java/com/create/chacha/domains/buyer/areas/mypage/controller/MypageReviewController.java
  src/main/java/com/create/chacha/domains/buyer/areas/mypage/service/MypageReviewService.java
  src/main/java/com/create/chacha/domains/buyer/areas/mypage/service/serviceImpl/MypageReviewServiceImpl.java
  src/main/java/com/create/chacha/domains/seller/areas/reviews/dto/response/ReviewListItemDTO.java
  src/main/java/com/create/chacha/domains/shared/repository/MypageReviewRepository.java
Labels: ✨ feat

#194 🐛 fix: 상품 리뷰 날짜 오류 수정
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/dto/response/ProductReviewResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/service/serviceimpl/ProductReviewServiceImpl.java
Labels: 🐛 fix

#196 🐛 fix: 클래스별 정산 이미지 안 뜨는 오류 수정
  src/main/java/com/create/chacha/domains/seller/areas/settlement/dto/response/ClassDailySettlementResponseDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/serviceimpl/SellerSettlementServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/SellerClassSettlementRepository.java
Labels: 🐛 fix

#203 🐛 fix: 클래스 수정 API 파라미터명 변경
  src/main/java/com/create/chacha/domains/seller/areas/classes/classcrud/controller/SellerClassesController.java
Labels: 🐛 fix

#207 ✨ feat: 주문 상태 카운트 4개 → 7개 확장 및 필드명 변경
  src/main/java/com/create/chacha/domains/seller/areas/main/dashboard/dto/response/OrderStatusCountResponseDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/main/dashboard/service/serviceimpl/SellerMainStatusServiceImpl.java
Labels: ✨ feat

#214 ✨ feat: 리뷰 수정/삭제 API 추가
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/controller/ProductReviewController.java
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/repository/ProductReviewRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/service/ProductReviewService.java
  src/main/java/com/create/chacha/domains/buyer/areas/reviews/service/serviceimpl/ProductReviewServiceImpl.java
Labels: ✨ feat
