Repository chachacreate/chachacreate_be, pull requests merged in 2025-08, with the labels that each got.

#10 ♻️ refactor: 관리자 메인 건수 조회 코드 재사용 구조로 리팩토링
  src/main/java/com/create/chacha/domains/admin/areas/main/requestcount/controller/AdminCountController.java
  src/main/java/com/create/chacha/domains/admin/areas/main/requestcount/dto/response/CountResponseDTO.java
  src/main/java/com/create/chacha/domains/admin/areas/main/requestcount/service/AdminCountService.java
  src/main/java/com/create/chacha/domains/admin/areas/main/requestcount/service/serviceimpl/AdminCountServiceImpl.java
Labels: ♻️ refactor

#28 ⏪ revert: 수정 완료된 ServiceImpl로 덮어쓰기 되돌림
  src/main/java/com/create/chacha/domains/admin/areas/main/requestcount/service/serviceimpl/AdminMainServiceImpl.java
Labels: ⏪️ revert

#31 ♻️ refactor: 스토어-구매자 상품섹션 구조 수정
  src/main/java/com/create/chacha/domains/buyer/areas/store/mainproduct/dto/response/ProductResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/store/mainproduct/repository/ProductQueryRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/store/mainproduct/service/serviceimpl/StoreMainProductServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/product/vo/ProductVO.java
Labels: ♻️ refactor

#35 ✨ feat: 클래스 페이지 조건조회 기능 추가
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/controller/ClassListController.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/dto/request/ClassListFilterDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/dto/response/ClassListResponseDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/repository/ClassInfoRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/ClassListService.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/serviceimpl/ClassListServiceImpl.java
Labels: ✨ feat

#37 ✨feat: 메인홈 - 날짜 선택 예약 가능 클래스 조회 API 기능 추가
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/controller/ClassListController.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/repository/ClassInfoRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/ClassListService.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/service/serviceimpl/ClassListServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/classes/vo/ClassCardVO.java
Labels: ✨ feat

#47 ✨ feat: 판매자-월별 클래스 예약 통계 API 추가
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/controller/SellerClassReservationStatsController.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/dto/response/SellerClassReservationStatsItemDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/dto/response/SellerClassReservationStatsResponseDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/service/SellerClassReservationStatsService.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/service/serviceimpl/SellerClassReservationStatsServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/ClassReservationStatsRepository.java
Labels: ✨ feat

#52 ✨ feat: 판매자 특정 클래스 월별 예약 통계 조회 API 추가
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/controller/SellerClassReservationStatsController.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/dto/response/SellerClassReservationStatsResponseDTO.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/service/SellerClassReservationStatsService.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/service/serviceimpl/SellerClassReservationStatsServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/ClassReservationStatsRepository.java
Labels: ✨ feat

#66 ♻️ refactor: API URI 컨벤션에 맞게 수정
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/controller/ClassReservationQueryController.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservationlist/controller/ClassReservationController.java
  src/main/java/com/create/chacha/domains/seller/areas/classes/reservations/controller/SellerClassReservationStatsController.java
Labels: ♻️ refactor

#72 🔧 update: 전체 클래스 목록 조회 API 수정
  src/main/java/com/create/chacha/domains/buyer/areas/classes/classlist/repository/ClassInfoRepository.java
  src/main/java/com/create/chacha/domains/shared/classes/vo/ClassCardVO.java
Labels: 🔧 update

#92 ✨ feat: 구매자 클래스 예약/결제 API 기능 추가
  src/main/java/com/create/chacha/common/constants/ResponseCode.java
  src/main/java/com/create/chacha/config/app/toss/TossProperties.java
  src/main/java/com/create/chacha/config/exception/GlobalExceptionHandler.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/controller/ClassReservationPaymentController.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/dto/request/ClassReservationPaymentRequestDTO.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/repository/ClassReservationPaymentRepository.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/service/ClassReservationPaymentService.java
  src/main/java/com/create/chacha/domains/buyer/areas/classes/reservations/service/serviceimpl/ClassReservationPaymentServiceImpl.java
  src/main/java/com/create/chacha/domains/buyer/exception/PaymentFailedException.java
  src/main/java/com/create/chacha/domains/buyer/exception/PaymentRequestException.java
  src/main/java/com/create/chacha/domains/buyer/exception/ReservationException.java
  src/main/java/com/create/chacha/domains/buyer/exception/ReservationSaveException.java
  src/main/java/com/create/chacha/domains/shared/repository/MemberRepository.java
Labels: ✨ feat

#107 ✨ feat: 판매자 - 특정 클래스 정산 조회 기능 추가
  src/main/java/com/create/chacha/domains/seller/areas/settlement/controller/SellerSettlementController.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/SellerSettlementService.java
  src/main/java/com/create/chacha/domains/seller/areas/settlement/service/serviceimpl/SellerSettlementServiceImpl.java
  src/main/java/com/create/chacha/domains/shared/repository/SellerClassSettlementRepository.java
Labels: ✨ feat
